---
title: "Malaysia Total Industry Volume (Vehicle Registrations)"
output:  
  flexdashboard::flex_dashboard:
    orientation: columns
    # social: menu
    # source_code: embed
---

<!-- # Malaysia Total Industry Volume (Vehicle Registrations) -->

This report provides an overview of vehicle registration trends in Malaysia, using JPJ data from `data.gov.my`.

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(DT)
library(ggplot2)
library(plotly)

car_data_path <- "data/car_data.csv"

car_data <- readr::read_csv(car_data_path)

# --- Find the most recent two full months ---
# (Ensures the code always uses the latest data)
latest_date <- max(car_data$date_reg)

year_current <- year(latest_date)
ytd_current_start <- ymd(paste0(year_current, "-01,-01"))
ytd_current_end <- latest_date

ytd_previous_start <- ytd_current_start %m-% years(1)
ytd_previous_end <- ytd_current_end %m-% years(1)

month_current <- latest_date
month_previous <- month_current %m-% months(1)
month_previous_year <- month_current %m-% months(12)

# Define all the relevant dates.
month_current_name <- format(month_current, "%b-%Y")
month_previous_name <- format(month_previous, "%b-%Y")
month_previous_year_name <- format(month_previous_year, "%b-%Y")
year_current_name <- paste0("YTD ", format(ytd_current_end, "%Y"))
year_previous_name <- paste0("YTD ", format(ytd_previous_end, "%Y"))
```

by Make
=======================================================================

```{r, include=FALSE}
# --- Calculate counts for each month and YTD ---
month_current_count <- car_data |>
  filter(date_reg == month_current) |>
  count(maker, name = "count_current")

month_previous_count <- car_data |>
  filter(date_reg == month_previous) |>
  count(maker, name = "count_previous")

month_previous_year_count <- car_data |>
  filter(date_reg == month_previous_year) |>
  count(maker, name = "count_previous_year")

ytd_current_count <- car_data |>
    filter(date_reg >= ytd_current_start & date_reg <= ytd_current_end) |>
    count(maker, name = "count_ytd_current")

ytd_previous_count <- car_data |>
    filter(date_reg >= ytd_previous_start & date_reg <= ytd_previous_end) |>
    count(maker, name = "count_ytd_previous")

# --- Join and calculate MoM growth ---
summary_data <- month_current_count |>
  full_join(month_previous_count, by = 'maker') |>
  full_join(month_previous_year_count, by = "maker") |>
  full_join(ytd_current_count, by = "maker") |>
  full_join(ytd_previous_count, by = "maker") |>
  mutate(
    count_current = replace_na(count_current, 0),
    count_previous = replace_na(count_previous, 0),
    count_previous_year = replace_na(count_previous_year, 0),
    count_ytd_current = replace_na(count_ytd_current, 0),
    count_ytd_previous = replace_na(count_ytd_previous, 0)
  ) |>
  mutate(
    growth_MoM = if_else(count_previous > 0, ((count_current/count_previous)-1), NA_real_),
    growth_YoY = if_else(count_previous_year > 0, ((count_current/count_previous_year)-1), NA_real_),
    growth_YTD = if_else(count_ytd_previous > 0, ((count_ytd_current/count_ytd_previous)-1), NA_real_),
    classification = case_when( maker %in% c("Perodua", "Proton") ~ "National", TRUE ~ "Non-National")
  ) |>
  arrange(desc(count_current)) |>
  mutate(rank = row_number()) |>
  select(rank, maker, count_current, count_previous, growth_MoM, count_previous_year, growth_YoY,
         count_ytd_current, count_ytd_previous, growth_YTD)
  
print(latest_date)
```

Column
-----------------------------------------------------------------------
### **Monthly Vehicle Registrations by Make**

```{r, echo=FALSE, message=FALSE}
# create a copy for the table to rename columns
table_display <- summary_data |>
    rename(
      `Rank` := rank,
      `Make` := maker,
      !!month_current_name := count_current,
      !!month_previous_name := count_previous,
      `Growth (MoM)` := growth_MoM,
      !!month_previous_year_name := count_previous_year,
      `Growth (YoY)` := growth_YoY,
      !!year_current_name := count_ytd_current,
      !!year_previous_name := count_ytd_previous,
      `Growth (YTD)` := growth_YTD
    )

# --- Create an interactive data table ---
datatable(table_display,
          rownames = FALSE,
          filter = 'top',
          # caption = 'Monthly Vehicles Registrations by Make',
          options = list(pageLength = 100, order = list(0, 'asc')),
          class = 'cell-border stripe') |>
  formatPercentage("Growth (MoM)", 1) |>
  formatPercentage("Growth (YoY)", 1) |>
  formatPercentage("Growth (YTD)", 1) |>
  formatStyle("Growth (MoM)", color = styleInterval(c(0), c('red', 'green'))) |>
  formatStyle("Growth (YoY)", color = styleInterval(c(0), c('red', 'green'))) |>
  formatStyle("Growth (YTD)", color = styleInterval(c(0), c('red', 'green')))
```

Column
-----------------------------------------------------------------------
### **Monthly Registration Trend by Make**

```{r, echo=FALSE, message=FALSE}
# --- Identify the top brands from latest month  ---
top_brands <- summary_data |>
  slice_head(n = 10) |>
  pull(maker)

# --- Prepare data for the time series plot ---
# Filter main data for top brands & count registrations by month
monthly_trends_data <- car_data |>
  filter(maker %in% top_brands) |>
  mutate(month = date_reg) |>
  count(month, maker, name = "registration")

# --- Create the plot ---
trend_plot <- ggplot(monthly_trends_data, aes(x = month, y = registration, color = maker)) +
  geom_line(linewidth = 0.5) +
  geom_point(size = 1.5) +
  labs(
    title = NULL,
    x = "Month",
    y = "Registration",
    color = NULL
  ) +
  theme_minimal(base_size = 14) +
  scale_y_continuous(labels = scales::comma)  # Put legend at the top

# --- Convert the ggplot object to an interactive plotly chart ---
ggplotly(trend_plot) |>
    layout(legend = list(
      # orientation = "h",
      # xanchor = "center",
      # x = 0.5,
      y = 0.5,
      font = list(size = 12)
    ))
```

by Model
=======================================================================

```{r, include=FALSE}
# --- Calculate counts for each month and YTD ---
month_current_count_model <- car_data |>
  filter(date_reg == month_current) |>
  count(maker, model, name = "count_current_model")

month_previous_count_model <- car_data |>
  filter(date_reg == month_previous) |>
  count(maker, model, name = "count_previous_model")

month_previous_year_count_model <- car_data |>
  filter(date_reg == month_previous_year) |>
  count(maker, model, name = "count_previous_year_model")

ytd_current_count_model <- car_data |>
    filter(date_reg >= ytd_current_start & date_reg <= ytd_current_end) |>
    count(maker, model, name = "count_ytd_current_model")

ytd_previous_count_model <- car_data |>
    filter(date_reg >= ytd_previous_start & date_reg <= ytd_previous_end) |>
    count(maker, model, name = "count_ytd_previous_model")

# --- Join and calculate MoM growth ---
summary_data_model <- month_current_count_model |>
  full_join(month_previous_count_model, by = c("maker", "model")) |>
  full_join(month_previous_year_count_model, by = c("maker", "model")) |>
  full_join(ytd_current_count_model, by = c("maker", "model")) |>
  full_join(ytd_previous_count_model, by = c("maker", "model")) |>
  mutate(
    count_current_model = replace_na(count_current_model, 0),
    count_previous_model = replace_na(count_previous_model, 0),
    count_previous_year_model = replace_na(count_previous_year_model, 0),
    count_ytd_current_model = replace_na(count_ytd_current_model, 0),
    count_ytd_previous_model = replace_na(count_ytd_previous_model, 0)
  ) |>
  mutate(
    growth_MoM = if_else(count_previous_model > 0, ((count_current_model/count_previous_model)-1), NA_real_),
    growth_YoY = if_else(count_previous_year_model > 0, ((count_current_model/count_previous_year_model)-1), NA_real_),
    growth_YTD = if_else(count_ytd_previous_model > 0, ((count_ytd_current_model/count_ytd_previous_model)-1), NA_real_),
  ) |>
  arrange(desc(count_current_model)) |>
  mutate(rank = row_number()) |>
  select(rank, maker, model, count_current_model, count_previous_model, growth_MoM, count_previous_year_model, growth_YoY,
         count_ytd_current_model, count_ytd_previous_model, growth_YTD)
```

Column
-----------------------------------------------------------------------
### **Monthly Vehicle Registrations by Model**

```{r, echo=FALSE, message=FALSE}
# create a copy for the table to rename columns
table_display <- summary_data_model |>
    rename(
      `Rank` := rank,
      `Make` := maker,
      `Model` := model,
      !!month_current_name := count_current_model,
      !!month_previous_name := count_previous_model,
      `Growth (MoM)` := growth_MoM,
      !!month_previous_year_name := count_previous_year_model,
      `Growth (YoY)` := growth_YoY,
      !!year_current_name := count_ytd_current_model,
      !!year_previous_name := count_ytd_previous_model,
      `Growth (YTD)` := growth_YTD
    )

# --- Create an interactive data table ---
datatable(table_display,
          rownames = FALSE,
          filter = 'top',
          # caption = 'Monthly Vehicle Registrations by Model',
          options = list(pageLength = 100, order = list(0, 'asc')),
          class = 'cell-border stripe') |>
  formatPercentage("Growth (MoM)", 1) |>
  formatPercentage("Growth (YoY)", 1) |>
  formatPercentage("Growth (YTD)", 1) |>
  formatStyle("Growth (MoM)", color = styleInterval(c(0), c('red', 'green'))) |>
  formatStyle("Growth (YoY)", color = styleInterval(c(0), c('red', 'green'))) |>
  formatStyle("Growth (YTD)", color = styleInterval(c(0), c('red', 'green')))
```

Column
-----------------------------------------------------------------------
### **Monthly Registration Trend by Model**

```{r, echo=FALSE, message=FALSE}
# --- Identify the top models from latest month  ---
top_models <- summary_data_model |>
  slice_head(n = 10) |>
  select(maker, model)

# --- Prepare data for the time series plot ---
# Filter main data for top brands & count registrations by month
monthly_trends_data_model <- car_data |>
  inner_join(top_models, by = c("maker", "model")) |>
  mutate(month = date_reg) |>
  count(month, maker, model, name = "registration") |>
  mutate(make_model = paste(maker, model, sep = " "))

# --- Create the plot ---
trend_plot_model <- ggplot(monthly_trends_data_model, aes(x = month, y = registration, color = make_model)) +
  geom_line(linewidth = 0.5) +
  geom_point(size = 1.5) +
  labs(
    title = NULL,
    x = "Month",
    y = "Registration",
    color = NULL
  ) +
  theme_minimal(base_size = 14) +
  scale_y_continuous(labels = scales::comma)  # Put legend at the top

# --- Convert the ggplot object to an interactive plotly chart ---
ggplotly(trend_plot_model) |>
    layout(legend = list(
      # orientation = "h",
      # xanchor = "center",
      # x = 0.5,
      y = 0.5,
      font = list(size = 12)
    ))
```

```{r, echo=FALSE, message=FALSE}
# --- Calculate counts for each month and YTD for fuel type ---
month_current_count_fuel <- car_data |>
  filter(date_reg == month_current) |>
  count(fuel_grouped, name = "count_current_fuel")

month_previous_count_fuel <- car_data |>
  filter(date_reg == month_previous) |>
  count(fuel_grouped, name = "count_previous_fuel")

month_previous_year_count_fuel <- car_data |>
  filter(date_reg == month_previous_year) |>
  count(fuel_grouped, name = "count_previous_year_fuel")

ytd_current_count_fuel <- car_data |>
    filter(date_reg >= ytd_current_start & date_reg <= ytd_current_end) |>
    count(fuel_grouped, name = "count_ytd_current_fuel")

ytd_previous_count_fuel <- car_data |>
    filter(date_reg >= ytd_previous_start & date_reg <= ytd_previous_end) |>
    count(fuel_grouped, name = "count_ytd_previous_fuel")

# --- Join and calculate MoM growth for fuel type ---
summary_data_fuel <- month_current_count_fuel |>
  full_join(month_previous_count_fuel, by = 'fuel_grouped') |>
  full_join(month_previous_year_count_fuel, by = "fuel_grouped") |>
  full_join(ytd_current_count_fuel, by = "fuel_grouped") |>
  full_join(ytd_previous_count_fuel, by = "fuel_grouped") |>
  mutate(
    count_current_fuel = replace_na(count_current_fuel, 0),
    count_previous_fuel = replace_na(count_previous_fuel, 0),
    count_previous_year_fuel = replace_na(count_previous_year_fuel, 0),
    count_ytd_current_fuel = replace_na(count_ytd_current_fuel, 0),
    count_ytd_previous_fuel = replace_na(count_ytd_previous_fuel, 0)
  ) |>
  mutate(
    growth_MoM_fuel = if_else(count_previous_fuel > 0, ((count_current_fuel/count_previous_fuel)-1), NA_real_),
    growth_YoY_fuel = if_else(count_previous_year_fuel > 0, ((count_current_fuel/count_previous_year_fuel)-1), NA_real_),
    growth_YTD_fuel = if_else(count_ytd_previous_fuel > 0, ((count_ytd_current_fuel/count_ytd_previous_fuel)-1), NA_real_) 
  ) |>
  arrange(desc(count_current_fuel)) |>
  mutate(rank = row_number()) |>
  select(rank, fuel_grouped, count_current_fuel, count_previous_fuel, growth_MoM_fuel, count_previous_year_fuel, growth_YoY_fuel, count_ytd_current_fuel, count_ytd_previous_fuel, growth_YTD_fuel)
```

by Fuel Type
=======================================================================

```{r, echo=FALSE, message=FALSE}
# --- Calculate counts for each month and YTD for fuel type ---
month_current_count_fuel <- car_data |>
  filter(date_reg == month_current) |>
  count(fuel_grouped, name = "count_current_fuel")

month_previous_count_fuel <- car_data |>
  filter(date_reg == month_previous) |>
  count(fuel_grouped, name = "count_previous_fuel")

month_previous_year_count_fuel <- car_data |>
  filter(date_reg == month_previous_year) |>
  count(fuel_grouped, name = "count_previous_year_fuel")

ytd_current_count_fuel <- car_data |>
    filter(date_reg >= ytd_current_start & date_reg <= ytd_current_end) |>
    count(fuel_grouped, name = "count_ytd_current_fuel")

ytd_previous_count_fuel <- car_data |>
    filter(date_reg >= ytd_previous_start & date_reg <= ytd_previous_end) |>
    count(fuel_grouped, name = "count_ytd_previous_fuel")

# --- Join and calculate MoM growth for fuel type ---
summary_data_fuel <- month_current_count_fuel |>
  full_join(month_previous_count_fuel, by = 'fuel_grouped') |>
  full_join(month_previous_year_count_fuel, by = "fuel_grouped") |>
  full_join(ytd_current_count_fuel, by = "fuel_grouped") |>
  full_join(ytd_previous_count_fuel, by = "fuel_grouped") |>
  mutate(
    count_current_fuel = replace_na(count_current_fuel, 0),
    count_previous_fuel = replace_na(count_previous_fuel, 0),
    count_previous_year_fuel = replace_na(count_previous_year_fuel, 0),
    count_ytd_current_fuel = replace_na(count_ytd_current_fuel, 0),
    count_ytd_previous_fuel = replace_na(count_ytd_previous_fuel, 0)
  ) |>
  mutate(
    growth_MoM_fuel = if_else(count_previous_fuel > 0, ((count_current_fuel/count_previous_fuel)-1), NA_real_),
    growth_YoY_fuel = if_else(count_previous_year_fuel > 0, ((count_current_fuel/count_previous_year_fuel)-1), NA_real_),
    growth_YTD_fuel = if_else(count_ytd_previous_fuel > 0, ((count_ytd_current_fuel/count_ytd_previous_fuel)-1), NA_real_) 
  ) |>
  arrange(desc(count_current_fuel)) |>
  mutate(rank = row_number()) |>
  select(rank, fuel_grouped, count_current_fuel, count_previous_fuel, growth_MoM_fuel, count_previous_year_fuel, growth_YoY_fuel, count_ytd_current_fuel, count_ytd_previous_fuel, growth_YTD_fuel)
```

Column
-----------------------------------------------------------------------
### **Monthly Vehicle Registrations by Fuel Type**

```{r, echo=FALSE, message=FALSE}
# create a copy for the table to rename columns
table_display_fuel <- summary_data_fuel |>
    rename(
      `Rank` := rank,
      `Fuel Type` := fuel_grouped,
      !!month_current_name := count_current_fuel,
      !!month_previous_name := count_previous_fuel,
      `Growth (MoM)` := growth_MoM_fuel,
      !!month_previous_year_name := count_previous_year_fuel,
      `Growth (YoY)` := growth_YoY_fuel,
      !!year_current_name := count_ytd_current_fuel,
      !!year_previous_name := count_ytd_previous_fuel,
      `Growth (YTD)` := growth_YTD_fuel
    )

# --- Create an interactive data table ---
datatable(table_display_fuel,
          rownames = FALSE,
          filter = 'top',
          # caption = 'Monthly Vehicles Registration by Fuel Type',
          options = list(pageLength = 100, order = list(0, 'asc')),
          class = 'cell-border stripe') |>
  formatPercentage("Growth (MoM)", 1) |>
  formatPercentage("Growth (YoY)", 1) |>
  formatPercentage("Growth (YTD)", 1) |>
  formatStyle("Growth (MoM)", color = styleInterval(c(0), c('red', 'green'))) |>
  formatStyle("Growth (YoY)", color = styleInterval(c(0), c('red', 'green'))) |>
  formatStyle("Growth (YTD)", color = styleInterval(c(0), c('red', 'green')))
```

Column
-----------------------------------------------------------------------
### **Monthly Registration Trend by Fuel Type**

```{r, echo=FALSE, message=FALSE}
# --- Prepare data for the time series plot ---
# Filter main data for top brands & count registrations by month
monthly_trends_data_fuel <- car_data |>
  mutate(month = date_reg) |>
  count(month, fuel_grouped, name = "registration")

# --- Create the plot ---
trend_plot_fuel <- ggplot(monthly_trends_data_fuel, aes(x = month, y = registration, color = fuel_grouped)) +
  geom_line(linewidth = 0.5) +
  geom_point(size = 1.5) +
  labs(
    title = NULL,
    x = "Month",
    y = "Registration",
    color = NULL
  ) +
  theme_minimal(base_size = 14) +
  scale_y_continuous(labels = scales::comma)  # Put legend at the top

# --- Convert the ggplot object to an interactive plotly chart ---
ggplotly(trend_plot_fuel) |>
    layout(legend = list(
      # orientation = "h",
      # xanchor = "center",
      # x = 0.5,
      y = 0.5,
      font = list(size = 12)
    ))
```
